### ISSUE TITLE
License UNKNOWN

### ISSUE THREAD

**Issue by jorgesumle** [sloria/pypi-cli#14]
```
> pypi info youtube-dl
youtube-dl
==========
YouTube video downloader

Latest release:   2016.12.12  

Last day:               0
Last week:              0
Last month:            90

Author:   Philipp Hagemeister
Author email: phihag@phihag.de

PyPI URL:  http://pypi.python.org/pypi/youtube_dl
Home Page: https://github.com/rg3/youtube-dl

License: UNKNOWN
```

The license should be "Public Domain" instead of "Unknown".

![youtube-dl](https://cloud.githubusercontent.com/assets/14212780/21083351/d027be30-bfee-11e6-9756-b847d3523bf8.png)

**Comment by jorgesumle** [comment]
The same problem with mps-youtube: https://pypi.python.org/pypi/mps-youtube/0.2.7.1

**Comment by ljesparis** [comment]
Hi.. it is not an issue.
when you upload a python package to pypi, you have to define package metadata...
if you see, youtube-dl does not include any license on its package.
for more information, review youtube-dl [setup.py](https://github.com/rg3/youtube-dl/blob/master/setup.py) file.

![pantallazo-2017-02-14 16-57-25](https://cloud.githubusercontent.com/assets/9313243/22948916/b00a1150-f2d6-11e6-928f-db17e7538b75.png)
